pr:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: InstallDependencies
  steps:
  - task: Npm@1
    inputs:
      command: "install"

- job: BuildProject
  steps:
  - task: Npm@1
    inputs:
      command: "custom"
      customCommand: 'run build'

- job: TestProject
  steps:
  - task: Npm@1
    inputs:
      command: "custom"
      customCommand: 'run build'
    